parameters:
- name: preview_ps
  displayName: PowerShell Preview Version
  type: string
  default: preview
- name: netCoreVersion
  displayName: .NET Version
  type: string
  default: 6.0.x

variables:
  winAgentPoolName: pool-windows-2019
  winAgentPoolVMImage: ''
  linuxAgentPoolName: pool-ubuntu-2004
  linuxAgentPoolVMImage: ''
  macOsAgentPoolName: Azure Pipelines
  macOsAgentPoolVMImage: macOS-11

pr: none
trigger: none

jobs:
- template: util/smoke-test-steps.yml
  parameters:
    name: 'Win_Preview_PS_SmokeTest'
    agentPoolName: ${{ variables.winAgentPoolName }}
    agentPoolVMImage: ${{ variables.winAgentPoolVMImage }}
    psVersion: ${{ parameters.preview_ps }}
    netCoreVersion: "7.0.x" 

- template: util/smoke-test-steps.yml
  parameters:
    name: 'Linux_Preview_PS_SmokeTest'
    agentPoolName: ${{ variables.linuxAgentPoolName }}
    agentPoolVMImage: ${{ variables.linuxAgentPoolVMImage }}
    psVersion: ${{ parameters.preview_ps }}
    netCoreVersion: "7.0.x"

- template: util/smoke-test-steps.yml
  parameters:
    name: 'MacOS_Preview_PS_SmokeTest'
    agentPoolName: ${{ variables.macOsAgentPoolName }}
    agentPoolVMImage: ${{ variables.macOsAgentPoolVMImage }}
    psVersion: ${{ parameters.preview_ps }}
    netCoreVersion: "7.0.x"