parameters:
- name: win_ps
  displayName: Windows PowerShell Version
  type: string
  default: 5.1.14
- name: ps7
  displayName: PowerShell 7.0.x Version
  type: string
  default: 7.0.*
- name: ps7_1
  displayName: PowerShell 7.1.x Version
  type: string
  default: 7.1.*
- name: ps7_2
  displayName: PowerShell 7.2.x Version
  type: string
  default: 7.2.*
- name: ps7_3
  displayName: PowerShell 7.3.x Version
  type: string
  default: 7.3.*
- name: latest_ps
  displayName: PowerShell Latest Version
  type: string
  default: latest
- name: ps_preview
  displayName: PowerShell Preview Version
  type: string
  default: preview
- name: netCoreVersion
  displayName: .NET Version
  type: string
  default: 6.0.x
- name: netCoreVersion_7
  displayName: .NET Version
  type: string
  default: 7.0.x


variables:
  winAgentPoolName: pool-windows-2019
  winAgentPoolVMImage: ''
  linuxAgentPoolName: pool-ubuntu-2004
  linuxAgentPoolVMImage: ''
  macOsAgentPoolName: Azure Pipelines
  macOsAgentPoolVMImage: macOS-11

pr: none
trigger: none

jobs:
- template: util/smoke-test-steps.yml
  parameters:
    name: 'Win_PS_Preview_SmokeTest'
    agentPoolName: ${{ variables.winAgentPoolName }}
    agentPoolVMImage: ${{ variables.winAgentPoolVMImage }}
    psVersion: ${{ parameters.ps_preview }}
    netCoreVersion: ${{ parameters.netCoreVersion_7 }}

- template: util/smoke-test-steps.yml
  parameters:
    name: 'Linux_PS_Preview_SmokeTest'
    agentPoolName: ${{ variables.linuxAgentPoolName }}
    agentPoolVMImage: ${{ variables.linuxAgentPoolVMImage }}
    psVersion: ${{ parameters.ps_preview }}
    netCoreVersion: ${{ parameters.netCoreVersion_7 }}

- template: util/smoke-test-steps.yml
  parameters:
    name: 'MacOS_PS_Preview_SmokeTest'
    agentPoolName: ${{ variables.macOsAgentPoolName }}
    agentPoolVMImage: ${{ variables.macOsAgentPoolVMImage }}
    psVersion: ${{ parameters._Preview }}
    netCoreVersion: ${{ parameters.netCoreVersion_7 }}