# Variable 'BotAccessToken' was defined in the Variables tab
# Multi-job configuration must be converted to matrix strategy: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#multi-job-configuration
parameters: 
- name: AzurePowerShellVersion
  displayName: The version of Azure PowerShell
  type: string
- name: IsLatestVersion
  displayName: Is the Azure PowerShell version the latest version
  type: boolean
  default: true

jobs:
- job: Job_1
  displayName: "Sync latest UX metadata files to Storage Blob"
  timeoutInMinutes: 90
  pool: pool-windows-2019
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: Compress the UX metadata files
    inputs:
      targetType: inline
      script: >-
        .\CompressUXMetadata.ps1
      workingDirectory: tools
  - task: AzurePowerShell@5
    displayName: Upload to Storage Blob
    inputs:
      targetType: inline
      script: >-
        $context = New-AzStorageContext -StorageAccountName "$(StorageAccountName)"
        If (${{ parameters.IsLatestVersion }})
        {
          Copy-Item "artifacts/UX.zip" -Destination "artifacts/azps-latest.zip"
          Get-Item "artifacts/azps-latest.zip" | Set-AzStorageBlobContent -Container $(StorageBlobContainerName) -Context $context -Force
        }
        $zipFile = "artifacts/${{ parameters.AzurePowerShellVersion }}.zip"
        Copy-Item "artifacts/UX.zip" -Destination $zipFile
        Get-Item $zipFile | Set-AzStorageBlobContent -Container $(StorageBlobContainerName) -Context $context -Force

